### ISSUE TITLE
Upgrading from 4.0.0 to 4.0.1 throws "uninitialized constant Capybara::DSL"

### ISSUE THREAD

**Issue by oboxodo** [site-prism/site_prism#155]
# Issue to raise for SitePrism framework

I'm guessing this issue is related to the latest changes regarding autoload.

We're using Capybara 3.39.1. When upgrading site_prism from 4.0.0 to 4.0.1 we get this error on load (running rspec or rails itself, same result):

```
$ RAILS_ENV=test bin/rails c
$ /home/oboxodo/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/site_prism-4.0.1/lib/site_prism/page.rb:14:in `<class:Page>': uninitialized constant Capybara::DSL

    include Capybara::DSL
                    ^^^^^ (NameError)
	from /home/oboxodo/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/site_prism-4.0.1/lib/site_prism/page.rb:13:in `<module:SitePrism>'
	from /home/oboxodo/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/site_prism-4.0.1/lib/site_prism/page.rb:3:in `<main>'
...
```

## Environment
- Operating System: Ubuntu
- What Gems / Versions you are using: capybara 3.39.1, site_prism 4.0.1
- How you're interacting with the Framework: Rspec
- Browser/s Driver/s being used - with version numbers: Cuprite 0.14.3

## Expected Behavior
Tests would run as they were running with v4.0.0.

## Actual Behavior
"uninitialized constant Capybara::DSL"

## Steps to reproduce
Upgrade from 4.0.0 to 4.0.1 then run any rails command loading the app in test env.

**Comment by luke-hill** [comment]
I need more info. The old issue has been fixed. Providing you're requiring site_prism it should load in capybara/dsl
